### ISSUE TITLE
Connect with Fair Code crew

### ISSUE THREAD

**Issue by chadwhitacre** [fairsource/fair.io#10]
Our vision for Fair Source overlaps a ton with [Fair-code](https://faircode.io/). Can we join forces?

I reached out in private email and also dropped a line https://github.com/faircode-io/faircode/pull/14, no response yet.

**Comment by chadwhitacre** [comment]
I ran into some folks at OS Summit NA who might be able to help make a connection. 🤞

**Comment by chadwhitacre** [comment]
Success! @janober and I just had a call. We are agreed in principle that our values and goals are aligned, and that it makes sense to move forward together under the Fair Source brand—he would have used it when launching Fair-code had it been available. 😁 Sentry is ready to invest in a full redesign of the [fair.io](https://fair.io/) website. We'll do that openly here on GitHub. When the time is right, we expect it will make sense to redirect [faircode.io](https://faircode.io/) to [fair.io](https://fair.io/).

Thank you @janober for kicking off Fair-code five years ago and for being willing to move forward together now! Yay!! 😍 🙌

**Comment by janober** [comment]
Uh, sorry. I totally missed the notification. I'm excited about fair-source and about finally getting closer to creating a real alternative to OSI approved open-source together.

**Comment by chadwhitacre** [comment]
Yay! No worries, you are busy. :-)
