### ISSUE TITLE
Feature request: delayed open source publication (with Use Limitation)

### ISSUE THREAD

**Issue by williamtheaker** [fairsource/fair.io#13]
Since this repo is kind of a Sentry project now (#9), are there any plans to add terms to the Fair Source License for eventually releasing software under an OSI-approved or DFSG-compatible license, like the "Grant of Future License" terms in Sentry's current license?

The Business Source License and Sentry's Functional Source License have built-in delayed relicensing terms, but those licenses seem to have a [different intent](https://mariadb.com/bsl-faq-mariadb/) than the Fair Source License version 0.9's "Use Limitation" restrictions, which is more of a "free trial" license in my eyes.

There are some projects[1] that I'm interested in contributing to that are license under the Fair Source License, version 0.9, presumably because the "Use Limitation" terms fit their business model better than the BSL, but before getting involved, I'd want to know that my work would eventually make its way into a free/libre release.

1: https://github.com/cirruslabs/tart for example

**Comment by chadwhitacre** [comment]
Thanks for chiming in and sorry this fell through the cracks. (I'm not sure exactly what was wrong with my notifications that I didn't see this in email, but I've added a route for `fairsource` org to my Sentry email so hopefully future notifications come through.)

The Fair Source License 0.9 is deprecated and we don't have any plans to publish new versions of it with additional terms. Honestly, I'm surprised to see a viable project using it. I did some searching early on and didn't come up with anything. If you know of other examples I'd love to hear about them. I'm about to kick off a project to build a new fair.io website, and one question with that will be what to do with the legacy license, whether to ignore it completely or give it its own page or what. If there are enough projects actually using it then it might be worth an explainer page.

**Comment by ezekg** [comment]
@chadwhitacre may be a helpful search: https://github.com/search?q=%22Fair%20Source%20License%22%20path%3ALICENSE*&type=code

**Comment by chadwhitacre** [comment]
Thanks. I think constraining to [`LICENSE.md`](https://github.com/search?q=%22Fair+Source+License%22+path%3ALICENSE.md&type=code) and [`LICENSE.txt`](https://github.com/search?q=%22Fair+Source+License%22+path%3ALICENSE.txt&type=code) is better, because it filters out `licenses.json` kinda stuff which is noisy.

**Comment by williamtheaker** [comment]
It seems like the original intent of the Fair Source License v0.9 was to create a built-in "free" (as in cost) tier, for attracting customers with a limited trial, whereas licenses like the Functional Source License v1.1, Elastic License v2, and the Business Source License 1.1 are focused on preventing competitors from undercutting you with cheaper hosted versions (see Elastic vs AWS).

I don't know if those two goals/approaches conflict with each other enough to require separate licenses though. While I wouldn't pick a nonfree license myself, I think it would be helpful to provide a migration path for projects that do find utility in the trialware model, but are also willing to eventually relicense older versions of the software under a free/open source license.

Here are some other recently active repos still using the Fair Source License version 0.9:

https://github.com/Parallels/prl-devops-service
https://github.com/UtilitechAS/amsreader-firmware
https://github.com/sudomakes/backroad
https://github.com/jitterted/tdd-game

**Comment by chadwhitacre** [comment]
Thanks @williamtheaker. Have you seen [PolyForm Countdown](https://polyformproject.org/licenses/countdown/1.0.0/)? More [on Kyle's blog](https://writing.kemitchell.com/2023/12/01/PolyForm-Countdown). Maybe that plus [another PolyForm license](https://polyformproject.org/licenses/) would meet your needs?

**Comment by williamtheaker** [comment]
> Maybe that plus [another PolyForm license](https://polyformproject.org/licenses/) would meet your needs?

I hadn't heard of these licenses before, but I don't want to help build proprietary software and all the PolyForm licenses are nonfree.

I'm closing this issue because I didn't realize a license had already been drafted in https://github.com/getsentry/fsl.software/issues/4, so it's all kind of moot anyways.
