### ISSUE TITLE
Thank you :heart: 

### ISSUE THREAD

**Issue by loicknuchel** [fairsource/fair.io#15]
I didn't want to pollute your other issue (https://github.com/fairsource/fair.io/issues/14) so creating a new one ^^
I'm making https://github.com/azimuttapp/azimutt and I'm scratching my head around Open Source vs company business.
This Fair Source proposal seems quite interesting and having the possibilities listed here is very valuable for me to understand a bit better the challenges.
Can't wait to see this evolve and will follow your launch in July :clap: 
So once again, thank you for that :+1:

**Comment by chadwhitacre** [comment]
Thank you @loicknuchel! Glad to hear we are on the right track. Best of luck with Azimutt! :)
