### ISSUE TITLE
Simplify our story with a single Fair Source License

### ISSUE THREAD

**Issue by chadwhitacre** [fairsource/fair.io#16]
### Problem Description

In conversations so far about Fair Source, I see two (related) points of confusion crop up regularly:

1. People think FSL stands for Fair Source License, not Functional Source License.
2. People conflate the _license_ (FSL, ELv2, SSPL) and the _model_ (Fair Source).

These two confusions add friction to our efforts to drive the change we want to see in the industry, which is a standardized, widely adopted approach for companies to safely, meaningfully share their core products.

### Solution Brainstorm

Promoting a single, flagship Fair Source License would resolve both confusions. What would it be?

Over at https://github.com/fairsource/fair.io/issues/14#issuecomment-2115549129, I identified [SSPL](https://www.mongodb.com/legal/licensing/server-side-public-license), [ELv2](https://www.elastic.co/blog/elastic-license-v2), and [FSL](https://fsl.software/) as the three concrete licenses that have enough traction and differentiation to justify promoting under a general Fair Source brand. 

**SSPL** is a license in the _copyleft_ (i.e., reciprocal, share-alike) tradition, introduced by MongoDB in 2018 and submitted for OSI approval. They [rejected](https://opensource.org/blog/the-sspl-is-not-an-open-source-license) it, but I hear rumors that there is another push gearing up to get something like SSPL approved by OSI ([this may be a nod](https://opensource.org/blog/practical-open-source-2024-submit-your-proposal) in that direction, e.g.). SSPL does seem to have a bit more traction than ELv2. Elastic themselves [dual-license under EL and SSPL](https://www.elastic.co/blog/licensing-change). Redis also [dual-licenses under RSAL and SSPL](https://redis.io/blog/redis-adopts-dual-source-available-licensing/). Elastic [aligned itself publicly](https://www.elastic.co/blog/elastic-license-update) with fair-code. I'm not finding anything similar from Mongo.

**ELv2** and **FSL-1.1** are both non-compete licenses in the _permissive_ Open Source tradition. Each has one unique feature:

- ELv2 allows for monetizing self-hosted with an optional license key.
- FSL-1.1 bakes in a conversion to Open Source after two years. 

I propose that we **fold these two licenses together into a Fair Source License** that would be, in @selviano's turn of phrase, "the flagship of the category." It would be suitable for 99%+ of adopters and consumers to use with minimal due diligence. Practically speaking, we would pick one license as the base and add the relevant language for the missing feature from the other. This would resolve both confusions identified above, which could really help this thing take off. As @selviano says:

> It's not exactly (or at all) how OSS evolved w/ licensing, but idk that it needs to be. A lot has changed in the world since open source started, and while its development/the existence and role of the OSI can serve as a guide, I think it would be misguided to try to recreate the movement.

**Comment by dcramer** [comment]
FSL and ELv2 do not do have the same goals. In particular, how do non-FSL licenses achieve the goal of more open source?

**Comment by chadwhitacre** [comment]
FSL has two goals:

1. Protect investment (don't care about self-hosted).
2. More Open Source.

ELv2 has one goal:

1. Protect investment (optionally care about self-hosted).

I'm proposing this for Fair Source License:

1. Protect investment (optionally care about self-hosted).
2. More Open Source.

I like "more open source" as a goal for Fair Source. Diregarding case-by-case variants of BSL, FSL is the only concrete licenses that achieve this goal. @ezekg has been an advocate of Fair Source to date and he monetizes self-hosted through ELv2. Are we writing him out?

**Comment by dcramer** [comment]
I'd rather consider renaming FSL to Fair Source License (i dont know that we should), and keeping space for a non-cloud-based version of FSL to resolve other concerns.

It's about values/agenda vs implementation for me, and its not obvious to me that EL shares our values or agenda, and could just be a positioning of protecting someones work while removing competition. That's fine, and totally reflects a large set of our values, but its a subset of what FSL is able to achieve with its time-delay and mandatory permissiveness.

**Comment by dcramer** [comment]
@ezekg to be clear (we're chatting in Slack), my point was more: Sentry is not going to adopt a license that adds more complexity/conditions. FSL is intended to keep it simple so it can remove adoption hurdles.

The complexity that FSL != Fair Source License to me is unrelated to ELv2/etc being "Fair Source", and the solution cannot be "Sentry changes to a license that adds a bunch of other conditions that no one will understand".

**Comment by ezekg** [comment]
Edited my above comment. I got confused i.r.t. the topic, sorry. Just like there isn't an "Open Source License", I don't think there needs to be a "Fair Source License" that is too flexible. Instead, I think having a variety of distinct flavors makes the most sense.

**Comment by chadwhitacre** [comment]
> If I had my perfect license, I'd write a license that was ELv2 (non-compete i.r.t SaaS, with commercial features protected by license key), but with a time limit like BUSL and FSL, where it would eventually become Open Source. Maybe I'll fund that someday.

Interesting. I wondered where you were at with this, thanks for speaking to it. Honestly I think it would take very little for FSL-1.1 to account for license keys or for ELv2 to sprout eventual Open Source conversion. Practically speaking the interaction of the two (license key + time delay) would be a non-issue because Apache/MIT would open up removal of the license gating. However, per @dcramer there is not appetite at Sentry for going either route, so after digesting with @selviano this is the messaging and approach he and I would like to bring to the table:

1. Rename Functional Source License to Fair Source License.
2. fair.io says:
    1. "Fair Source is a great way to meaningfully, safely share your company's core products."
    2. "Want to adopt Fair Source? Here's the playbook:
        1. apply Fair Source License,
        2. audit for secrets,
        3. make it public,
        4. announce 'Foo is now Fair Source'
    3. "FAQ"
        1. "What if I want to monetize self-hosted? Fair Source License is not for you, look into ELv2."
        2. "What if I like copyleft? Fair Source License is not for you, look into SSPL."
        3. "Can I still call it Fair Source if I use ELv2 or SSPL? Yes, of course. Any good faith attempt to meaningfully, safely share your company's core products counts as Fair Source."
        4. etc.

This hopefully accomplishes the following:

1. Addresses @dcramer thinking on requirements ("meaningfully, safely sharing core products") vs. recommendations (FSL approach w/ unmonetized self-hosted and 2-year dosp)
2. Acknowledges ELv2 and SSPL (and maybe other approaches?).
3. Eases onboarding for new adopters (opinionated default w/ suggested alternatives).
4. Tunes for adoption of "Fair Source" term through relaxed approached compared with "Open Source" hardliners.

**Comment by dcramer** [comment]
> Practically speaking the interaction of the two (license key + time delay) would be a non-issue because Apache/MIT would open up removal of the license gating.

I dont think its black and white. I think its more likely that a court would see it as contradictory, and from a legal practice point of view, you want licenses to be very, very clear. When the code converts, its technically permissive, but the license of the current software says you can't mess with the feature gate. Those two things contradict each other, as once the code is permissive, you could simply remove the feature gate and redistribute it.

IMO the only way you can have a successful traditional open core license that has a conversion (to anything incompatible, like permissive), would be by having a separation of the code. To me the two goals are, arguably, mutually exclusive. I realize the open core approach is more traditional in software that has to operate behind the firewall, and maybe there's not a better solution there without doing an actual code split.

**Comment by chadwhitacre** [comment]
> I wasn't under the impression that we were merging or conflating licenses; rather, creating an umbrella term

That is where we started, yes, because that is how OSI evolved and OSI has been our de facto template. But, when I [dug into the details](https://github.com/fairsource/fair.io/issues/14#issuecomment-2115549129), there are only three licenses with meaningful traction, two of which turn out to be quite close: ELv2 and FSL. They're both permissive-style non-competes. One allows for optionally monetizing self-hosted use. The other allows for eventual Open Source. I'm more optimistic than @dcramer that someone could craft a harmonized license that includes both features.

The third real contender, SSPL, is hyper-copyleft and wants to be OSI approved. I see an opportunity to brand Fair Source as permissive non-compete and let SSPL proponents go chase after OSI.

> Just like there isn't an "Open Source License", I don't think there needs to be a flexible "Fair Source License."

There doesn't _need_ to be but if there _could_ be then that would have the benefit of minimizing decision fatigue, which would greatly help onboard the next 1,000 Fair Source adopters.

I don't want to have two close-but-different brands to push:

- **FSL** is simple permissive-style non-compete with 2-year-eventual Open Source. It is the recommended approach to Fair Source but no it doesn't stand for Fair Source License and no you can't monetize local use.
- **Fair Source** is a big tent of our recommended approach FSL which converts to Open Source in 2 years (but no it doesn't stand for Fair Source License and no you can't monetize local use) and also a bunch of watered down approaches that _don't_ convert to Open Source like ELv2 and SSPL and ... and ... and ...

The fact that OSI lists an [Open Software License](https://opensource.org/license/osl-3-0-php) actually proves the point: no-one uses OSL. None of us had heard of it until we went looking during this conversation. However, we want FSL to be the flagship license for Fair Source. We _want_ FSL and Fair Source to be synonymous for 99%+ of people.

> Instead, I think having a variety of distinct flavors makes the most sense. Keeping the flavors focused on a particular monetization strategy (and values) seems like a good goal to have.

The **values** are the same as ever: [freedom + sustainability](https://blog.sentry.io/sentrys-open-source-values/).

The **goal** is settled: wide adoption of companies safely, meaningfully sharing their core products.

There are only two possible **monetization strategies**, because there are only two possible **distribution strategies**: _cloud_ and _local_ (of which self-hosted is a particular case for complete products; library usage is the other big bucket under local).

@dcramer brought up in private chat that there are a bunch of licenses that do things like "free up to 25 seats" or "free up to 600 million public users if the license owner is a social network." Those could all be handled by a generic license key functionality such as ELv2 includes. We don't risk license proliferation by bringing in license keys, we _reduce_ the risk by providing a standard way to license local usage in addition to SaaS.

In other words, I don't think there's a variety of distinct flavors, when we dig into details. Even with OSI there are hundreds of licenses but only a handful that matter (Apache, MIT, GPL). As @selviano says in the quote above: "It's not exactly (or at all) how OSS evolved w/ licensing, but idk that it needs to be. A lot has changed in the world since open source started, and while its development/the existence and role of the OSI can serve as a guide, I think it would be misguided to try to recreate the movement."

> Maybe I'll fund that someday.

@ezekg If you want to push for this I'm all in favor. @hmeeker worked with us pro bono on FSL. At the risk of putting her on the spot I suspect she'd be willing to do the same for the Keygen Source License(!).

Personally I think we could get to a single Fair Source License that handles both Keygen's and Sentry's use cases. I think that makes sense to get done together under a "Fair Source" banner that Sentry is investing in but is larger than just us (supposedly). I think it will be weird when you come back to us with [an ELv2 with FSL-1.1's "Grant of Future License" clause tacked on](https://docs.google.com/document/d/1NAhTUU6xmyz6-I217HGkilPZsLnKnVHrCa1S6O6U37M/edit?usp=sharing) and call it the Keygen Source License and now we have to sort out how we're positioning the Fair Source License = FSL-1.1 vs. Keygen Source License which would meet the criteria to be a recommended approach and are we gonna call it Fair Core License maybe that would work. I guess we can cross that bridge when we come to it, but it seems short-sighted to me not to get that done now or at least plan for it since it's right in front of us.

> what's the point of taking over "fair source" when it was already defined (albeit not popular), and already included ELv2?

Don't forget [Fair Source was a concrete license](https://fair.io/legacy.html) when we took it over. You're confusing this with [Fair-code](https://faircode.io/), which is a generalized model created _after_ the original Fair Source License. This is a case of confusing the license and the model, in other words—one of the two problems this ticket set out to solve. ;-)

**Comment by chadwhitacre** [comment]
Alright, so I'm gonna dial back out to #14 on the basis of https://github.com/fairsource/fair.io/issues/16#issuecomment-2146232306, and I've also ticketed #17 to track writing a separate Fair Core License. Closing here, thanks all.
