### ISSUE TITLE
Define governance

### ISSUE THREAD

**Issue by chadwhitacre** [fairsource/fair.io#20]
I've been asked about the governance model for Fair Source. My answer was, "We have multiple launch partners and a public GitHub issue tracker, and we'll evolve from there." Now I've been asked again by a potential adopter, which makes me think that we'll need to evolve sooner rather than later. :)

So I'm opening a thread here to discuss. Obviously Sentry is going to want to keep a hand on the rudder, but I do think it would be healthy to have people from outside of Sentry involved in decision-making for Fair Source. This should be a true community effort. Table stakes should of course be adopting Fair Source for your company (though here prior to launch we're in a bit of a chicken-and-egg).

In my view, @ezekg—you are really the best candidate to form a steering committee together with myself since you've been highly involved from the beginning, going so far as to write your own license to populate the "DOSP + license keys" niche. There are other Sentry folks who have been involved, especially @selviano and @GavinZee. I think we should have one vote/rep/whatever per company. Maybe a standing monthly call is in order? I'm not sure how much business there will be to transact after the initial launch here.

Anyway, I wanted to start the conversation. Thoughts?

**Comment by ezekg** [comment]
Appreciate it. I'm for it if we think it's something that would help encourage adoption. I like the idea of 1 vote per entity using a Fair Source license because it'll help solidify the fact that Fair Source isn't controlled by a single entity.

**Comment by chadwhitacre** [comment]
> inclusion of new entities

I guess really the decision point is adding companies to the company listing, it means reviewing their blog post or link, and digging a little deeper to see that they've adopted a Fair Source licensing approach (which could get futzy if they use something other than one of the five official licenses). I think we could keep it small for the foreseeable future, I don't think we'll get a thundering herd of adoption.

Beyond that I guess it's questions about the values and definition of Fair Source, and whether to formally recognize additional licenses.

**Comment by ezekg** [comment]
All fine by me. I'm for it. A monthly or quarterly call works.

**Comment by ezekg** [comment]
To clarify, I meant inclusion of new entities that have voting power i.r.t. this governance model, not new entities that are allowed to adopt Fair Source. Just want to make that crystal clear since my original comment was a bit ambiguous reading it back.

**Comment by chadwhitacre** [comment]
I'm planning to move forward with a simple setup where @ezekg and I are the steering group, and our responsibilities are to:

1. Vet new licenses against the Definition as they are submitted.
2. Vet new company announcements as they are submitted (review license, if BUSL review further).

I intend to add some notes to the README tomorrow after #25 lands.

**Comment by chadwhitacre** [comment]
I stubbed a readme in #27. Gonna add some notes there ...
