### ISSUE TITLE
Add Ptah.sh to the companies who love FSL

### ISSUE THREAD

**Issue by bohdan-shulha** [fairsource/fair.io#37]
Hey. :)

It seems to be enough motivation for me to jump straight into publishing an article. :D

<img width="614" alt="image" src="https://github.com/user-attachments/assets/102e3a6c-40d1-4022-acfd-c69e9419b7cb">

This is the link to the publication:
https://ptah.sh/blog/2024-08-09-we-use-fair-source/

This the announcement on the company's social page:
https://x.com/ptah_sh/status/1821894028838723991

**Comment by ezekg** [comment]
One minor correction on the blog post is that there is no Fair Source License. I think you meant to refer to the Functional Source License. Let's change that to avoid confusion since Fair Source is an umbrella term for a few different licenses right now.

**Comment by bohdan-shulha** [comment]
Ah, sorry. Will fix in a minute.

**Comment by bohdan-shulha** [comment]
Please take a look at the changes.

Fixed up the references and added a link to the FSL itself.

**Comment by chadwhitacre** [comment]
Huzzah! Thanks for being our first post-launch adopter, @bohdan-shulha! 😍

I've made a PR for us: https://github.com/fairsource/fair.io/pull/38. Wanna give us a thumbs up over there if it looks okay?

**Comment by bohdan-shulha** [comment]
Yes, sure, please proceed. I can't describe how much excited I am now. :D

**Comment by ezekg** [comment]
@bohdan-shulha I see quite a few places on your website and repository (e.g. readme) that refers to the project as open source. I want to make sure that projects licensed under fair source licenses, especially those listed on the website, correctly refer to their projects as fair source and not open source. I'd like to avoid any confusion there.

Would you mind updating the verbiage throughout your website and repos to use fair source when referring to software licensed under the FSL?

**Comment by bohdan-shulha** [comment]
@ezekg , yeah, I have noticed it yesterday as well and was thinking to fix soon.

I'll re-phrase everything through the day or two.

Thanks.

**Comment by bohdan-shulha** [comment]
JFYI, fixed the landing and the primary repository wording (Open => Fair).
