### ISSUE TITLE
Add Happybase

### ISSUE THREAD

**Issue by chadwhitacre** [fairsource/fair.io#39]
From @jdbohrman:

https://x.com/james_bohrman/status/1821578526828437789
&nbsp; &nbsp; ↳ https://www.happybase.co/blog/what-i-learned-from-dogfooding/
&nbsp; &nbsp; &nbsp; &nbsp; ↳ https://github.com/happycharts/happybase

The "What I learned" post assumes Fair Source without really going into detail. Is that enough for us here @ezekg? Do we need a post specifically about Fair Source and the decision to go that route? I can see it both ways ...

**Comment by ezekg** [comment]
I'd like to see a post specifically covering why @jdbohrman decided to adopt fair source so that we can maintain the viral and contagious nature of these posts.

**Comment by jdbohrman** [comment]
@ezekg Happy to do that for sure, I'll work on that later today!

**Comment by chadwhitacre** [comment]
Noooo! I just saw #33, not sure how I missed that. Let's close this one as a dupe, sorry about that @jdbohrman! 🐭
