### ISSUE TITLE
Review Directus

### ISSUE THREAD

**Issue by chadwhitacre** [fairsource/fair.io#41]
@rijkvanzanten [asks](https://x.com/rijkvanzanten/status/1819514599604994221) if [Directus' BSL](https://github.com/directus/directus/blob/e2b4012060b0aee5d4f3ddd8298d8a1e49901a67/license) fits.

**Comment by rijkvanzanten** [comment]
How is "undue burden" defined and how does one measure whether or not a burden is undue? 🤔

**Comment by rijkvanzanten** [comment]
And to follow up to the same question, as per the website the FSL describes it as:

> You can do anything with FSL software except undermine its producer.

https://fsl.software/

How does the end-user know if they're undermining the software producer and is that an undue burden?

(Sorry for being difficult, just trying to wrap my head around the details here 🙂 )

**Comment by ezekg** [comment]
The problem I see with this type of revenue-based restriction is that there are no clear next steps in the license when the revenue threshold is met, and it puts undue burden on the licensee to audit themselves. So just to clarify — is your usage of BUSL allowing competing uses in BaaS/SaaS, as long as the competitor is under $5MM in revenue/funding/etc.?

**Comment by rijkvanzanten** [comment]
We noticed that the majority of contributors (in both time and donations) of Directus where hobbyists/individuals and small/growing companies, whereas companies that extracted the most value out of the project would contribute the least. To combat that, we adopted the BSL 1.1 license which by default doesn't allow for any production use (emphasis mine):

> The Licensor hereby grants you the right to copy, modify, create derivative works, redistribute, and make **non-production use** of the Licensed Work.

To make sure we don't punish the folks who already contribute their fair share in time, added in the additional use grant to allow them to use it in production for free still.

**Comment by rijkvanzanten** [comment]
> I'm just trying to wrap my head around why something like FSL is not feasible for your business model.

The problem is the interpretation of Permitted Usage. The current permitted usage seems oriented around source available SaaS platforms, but feels a bit trickier for self-hosted software packages.

Directus is a backend/cms, which means that "internal use and access" is the main commercial usage of the project, and "offers the same or substantially similar functionality as the Software" is something that you can easily argue is the case when using the backend APIs to integrate with other third parties 🤔

**Comment by ezekg** [comment]
> Edit: Another important vision thing here is that we are trying not to end up with an "open core" style model where we have a "free" / "community" edition that's fair source but limited, and a "pro" version that's closed source and paid 🙂

Just an aside — have you looked at the [Fair Core License](https://fcl.dev)? I helped author the FCL so that the "pro" version does not need to be closed source, but can be licensed under fair source and eventually open sourced just like the rest of code base.

As I mentioned, I'm still concerned that revenue-based restrictions may place too much burden on the licensee.

**Comment by chadwhitacre** [comment]
> How is "undue burden" defined and how does one measure whether or not a burden is undue

This means that I should be able to run your software OOTB without having to ask myself the question, I am complying or not? For FSL this is true because it takes a lot of work to turn a standalone app into a SaaS. For FCL this is true because the license key prevents me from accessing commercial features.

**Comment by chadwhitacre** [comment]
I see the license key avenue as supportive of a number of restriction strategies: feature gates, user seats, processing volume, etc. Not revenue necessarily but perhaps some suitable proxies available?

**Comment by ezekg** [comment]
More context: https://directus.io/bsl-faq. Mentions using [Unity's revenue-based license restrictions](https://unity.com/legal/editor-terms-of-service/software) as inspiration. Even Unity's restrictions seem to be on an honor-system, which is again, hard to enforce and puts undue burden on the licensee.

**Comment by rijkvanzanten** [comment]
Thanks for the insights all! I had not heard of the FCL flavor before @ezekg, looks very interesting and could be a perfect match :) Very excited to see new movements in this open source space. At the time we changed, the BSL with additional usage grants was really the only viable option available, so very excited to see this new push into a more standardized open-but-sustainable licensing model 🫶 

Our intent here was/is to make sure we don't 'punish' the folks who are already contributing by bucketing them into the same paid model as the bigger orgs who didn't contribute as much if at all. The current iteration is by trying to bake that in to the license itself, but that's indeed not very common[^1]. There's always the alternative to make the license cover everybody and every use so there's no undue burden (as now everybody gotta pay), and handle the first intent through discounts and the like.

Appreciate the open discussion around this. It's a subject close to heart, and one that stands or falls by the adoption of as many projects as possible. 

[^1]: although it looks like mr Perens is using the same threshold for a new Post-Open movement, which is similar in spirit but very different in execution https://www.theregister.com/2024/04/30/bruce_perens_post_open_license/

**Comment by ezekg** [comment]
> There's always the alternative to make the license cover everybody and every use so there's no undue burden (as now everybody gotta pay), and handle the first intent through discounts and the like.

in that case, I'm not sure that would fall under "minimal restrictions", a requirement covered in the [Fair Source Definition](https://fair.io/about/). Rather, that'd fall more into source-available/propriety software since it couldn't be used by anybody without a license key.

Under the FCL, ideally, you'd offer a substantial portion of the software for free and sell license keys to your target demographic of med-large businesses.

**Comment by chadwhitacre** [comment]
I think we can bring this current thread in for a landing, and if/when Directus moves forward with a modified licensing scheme we can reopen. Reasonable?

**Comment by rijkvanzanten** [comment]
> Rather, that'd fall more into source-available/propriety software since it couldn't be used by anybody without a license key.

Yeah totally, personally not a fan of that. Just thinking aloud here 🙂 

> I think we can bring this current thread in for a landing, and if/when Directus moves forward with a modified licensing scheme we can reopen. Reasonable?

Yes, fair enough! (pun intended)

**Comment by chadwhitacre** [comment]
Sounds good. Thanks for thinking through this with us, @rijkvanzanten. Best of luck and I hope to see you here again in the future! 😁
