### ISSUE TITLE
Add a `.gitignore`

### ISSUE THREAD

**Issue by rijkvanzanten** [fairsource/fair.io#42]
I don't believe `.DS_Store`, `node_modules`, nor `.vscode` are intended to be in the `main` branch of the repo, but correct me if I'm wrong!

Happy to open a PR to resolve if wanted.

**Comment by chadwhitacre** [comment]
Oops! Agreed, let's clean that up. A PR would be great @rijkvanzanten, thanks. :)

I did find [this advice re: `.vscode`](https://stackoverflow.com/a/57749909). Seem reasonable?

**Comment by rijkvanzanten** [comment]
> I did find [this advice re: .vscode](https://stackoverflow.com/a/57749909). Seem reasonable?

IMO If important build steps or configuration is stored in `.vscode` settings specifically, it means you're alienating folks who don't use vs code 🤔 That being said, you could also view it from the other side and say that we're progressively enhancing the DX for people using vs code.  There's also a potential conflict where personal preferences bleed out to the rest of the team (f.e. if I set the project-settings to tabs instead of spaces).

Either way I'll include the recommended gitignore for the vscode settings 👍🏻
