### ISSUE TITLE
Add FAQ about legacy license

### ISSUE THREAD

**Issue by chadwhitacre** [fairsource/fair.io#48]
Not sure how persistent the confusion will be. Seeing a bit of it but it seems forced (to try to make us look bad?):

https://lobste.rs/s/gc6has/fair_source_licensing_is_worst_thing
https://news.ycombinator.com/item?id=41349252

**Comment by chadwhitacre** [comment]
([X cross-reference](https://x.com/Dieter_be/status/1828361133343805788))

**Comment by chadwhitacre** [comment]
@Dieterbe Up for a PR? 😁

**Comment by Dieterbe** [comment]
i mean, i lack some background info here that you presumably have, but maybe the above PR is a good start..

**Comment by chadwhitacre** [comment]
Yay, thanks! Moving to #49 ...

**Comment by chadwhitacre** [comment]
Calling this good. Thanks, team!
